language: python
python:
  - "2.7"
  - "2.6"
install: pip install -r restclients/requirements.txt
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - cp travis-ci/manage.py manage.py
  - python manage.py syncdb --noinput
script:
  - pep8 --exclude=migrations restclients/
  - coverage run --source=restclients manage.py test restclients
after_script:
  - coveralls
notifications:
  webhooks:
      urls:
        - https://yarn.cac.washington.edu/rest/botalyst/v1/travis-ci
