development:
    host   : "iam-tools.u.washington.edu"
    port   : 443
    cert   : ""
    key    : "" 
    log    : ""
    timeout: 500

production:
    host   : "iam-ws.u.washington.edu"
    port   : 7443
    cert   : ""
    key    : ""
    log    : ""
    timeout: 500
